name: 'S3-Satis'
description: 'Build Satis Composer repository on S3'
inputs:
  satis-config-path:
    description: 'Path to Satis repository config file'
    default: 'satis.json'
    
  s3-satis-version-tag:
    description: 'Docker tag to use'
    default: 'v0'

  repository-url:
    required: false
    description: URL of repository to update
    
  verbosity:
    type: choice
    description: Verbose Level
    default: 'normal'
    options: 
    - normal
    - verbose
    - very_verbose
    
  use-cache:
    type: boolean
    description: Do you want to use data from cache directory?
    default: false
    
  fresh:
    type: boolean
    description: Do you want fully recreate repository from scratch?
    default: false
    
  cache-path:
    description: 'Cache directory path'
    default: 'satis-cache'
    
  s3-access-key-id:
    description: 'S3 Access Key Id'
    required: true
    
  s3-secret-access-key:
    description: 'S3 Secret Access Key'
    required: true
    
  s3-region:
    description: 'S3 Region'
    default: 'us-east-1'
    
  s3-bucket:
    description: 'S3 Bucket'
    required: true
    
  s3-endpoint:
    description: 'S3 Endpoint'
    required: false
    
  s3-use-path-style-endpoint:
    description: 'S3 Use path style endpoints'
    default: false
    
runs:
  using: "composite"
  steps:
    - name: Build Satis Repo
      shell: bash
      run: |
        docker run \
          --volume "${PWD}/${{ inputs.satis-config-path }}:/usr/src/satis/satis.json" \
          --volume "${PWD}/${{ inputs.cache-path }}/:/usr/src/satis/satis-cache/" \
          --volume "${COMPOSER_HOME:-$HOME/.composer}:/root/.composer/" \
          --env S3_ACCESS_KEY_ID=${{ inputs.s3-access-key-id }} \
          --env S3_SECRET_ACCESS_KEY=${{ inputs.s3-secret-access-key }} \
          --env S3_REGION=${{ inputs.s3-region }} \
          --env S3_BUCKET=${{ inputs.s3-bucket }} \
          ${{ inputs.s3-endpoint != '' && format('--env S3_ENDPOINT="{0}"', inputs.s3-endpoint) || '' }} \
          --env S3_USE_PATH_STYLE_ENDPOINT=${{ inputs.s3-use-path-style-endpoint }} \
          ghcr.io/kduma-oss/s3-satis:${{ inputs.s3-satis-version-tag }} build \
          ${{ inputs.fresh == 'true' && '--fresh' || '' }} \
          ${{ inputs.verbosity == 'verbose' && '-v' || '' }} \
          ${{ inputs.verbosity == 'very_verbose' && '-vvv' || '' }} \
          ${{ inputs.use-cache == 'true' && '--set-extension=cache:path=/usr/src/satis/satis-cache/' || '--set-extension=cache:enabled=false'}} \
          ${{ inputs.repository-url != '' && format('--repository-url="{0}"', inputs.repository-url) || '' }}